### PR TITLE
Add builds for OSX and Windows

### PR DESCRIPTION
**Pull request by jonatasbaldin**
Hey there!

This PR adds a step into the build process to create a binary for the darwin/amd64 and windows/amd64 architectures.

### CODE REVIEW

**Comment by pst** [comment]
Thanks for the contribution.

I'm not quite sure about the immediate value of this though. Building the Windows and Darwin binaries during the tests will increase the time for test runs. But since the tests are only run on Linux, the binaries would never be used.

If there is a way to also run the same test suite on Darwin and Windows using Github Actions building the binaries would make sense.

Ultimately, the tested binaries should also be used as the binaries attached to releases. This is currently not the case either.

**Comment by nikolay** [comment]
The main benefit is that people on macOS and Windows don't have to compile the provider.

**Comment by pst** [comment]
As I said, the change does only build for the two other OS'. It does not attach the binaries to a release.

**Comment by pst** [comment]
I'm closing this pull request due to lack of activity. Feel free to open a new one, if you'd like to contribute to providing release binaries for mac and windows.

**Comment by jonatasbaldin** [comment]
Hey there, completely forgot about this one 😅 

Since you are doing the release manually, what about exposing the binaries as an artifact in the Github Actions and you can just download/attach them after the pipeline is run?

Cheers!

**Pull request closed without merging**
