### PR TITLE
Add context to provider + refactor kubeconfig data loading

### PR DESCRIPTION
**Pull request by maxiaohao**
It becomes dangerous when applying kustomization across multiple kubernetes contexts. For now we have to ensure we've switched to the right context before a terraform apply. This PR resolves the problem by allowing specifying the kubernetes context name in the terraform provider:
- [x] Added an optional kubernetes `context` to the provider.
- [x] Refactored kubeconfig data loading behaviour. Before it tries in the order of `kubeconfig_raw -> kubeconfig_path -> defaut client (useless and misleading)`, now it doesn't try or fallback at all, instead it's like "use `kubeconfig_raw` if it is set, otherwise use `kubeconfig_path`". I made this change because I found a bad `kubeconfig_raw` could cause the tool to silently fallback to `kubeconfig_path` making an illusion that the `kubeconfig_raw` was "still working", which is not expected at all.

### CODE REVIEW

**Comment by pst** [comment]
Thank you for your contribution @maxiaohao. Adding the context parameter is fine.

But, the fallback to the default client is used to allow creating a Kubernetes cluster and creating K8s resources on that cluster in one apply run. Have you verified, that your change does not break this?

Please remove the commit that adds your IDE specific file to the `.gitignore`.

**Comment by maxiaohao** [comment]
Hi @pst , 

Glad to see you accept adding the context parameter.

I've removed the .iml entry from .gitignore. 

Regarding fallback to default client, the new logic removed it and now just returns the error if loading `kubeconfig_raw` or `kubeconfig_file` fails. If I understand correctly, the deafult client assumes a local kubernetes cluster endpoint running at `http://localhost/api`, as I don't have such a local cluster the build from master branch just throw me an error `Error: ResourceExists: discovering API group resources failed: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused` if I misconfigure both `kubeconfig_raw` and `kubeconfig_file`. 

I still feel the fallback to such a default client is unexpected - my immediate feeling on that error message led me to examine what's wrong in `kubeconfig_raw` or `kubeconfig_file` and I would never expect the tool could have silently pointed to `http://localhost/api`. On the other hand, even if I had a local cluster running at `http://localhost/api` I should have it properly configured in `~/.kube/config` then it would be working with the default `kubeconfig_file`.

Note in this PR I intentionally removed the auto fallbacks, i.e., if I set some value to `kubeconfig_raw` in provider, it should only work with `kubeconfig_raw` and in case it's invalid the program is not to fallback to `kubeconfig_file`, instead it should immediately echo what's wrong with `kubeconfig_raw` rather than incorrectly applying things into the irrelevant cluster defined in your `~/.kube/config` (`kubeconfig_file`'s default) which could be disastrous.

**Comment by pst** [comment]
I see your argument, it's weird to try to connect to a nonexistent cluster on localhost. But it's what `kubectl` does.

It's used, so that given a configuration like this:

```hcl
provider "kind" {}

resource "kind" "example" {
  name = "test"
}

provider "kustomization" {
  kubeconfig_raw = kind.example.kubeconfig
}

data "kustomization" "example" {
  path = "base"
}

resource "kustomization_resource" "example" {
  for_each = data.kustomization.example.ids

  manifest = data.kustomization.example.manifests[each.value]
}

```

The current implementation will plan to first create a cluster, then use the returned `kubeconfig` to provision the k8s resources.

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.kustomization.example: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # kind.example will be created
  + resource "kind" "example" {
      + client_certificate     = (known after apply)
      + client_key             = (known after apply)
      + cluster_ca_certificate = (known after apply)
      + endpoint               = (known after apply)
      + id                     = (known after apply)
      + kubeconfig             = (known after apply)
      + kubeconfig_path        = (known after apply)
      + name                   = "test"
      + node_image             = (known after apply)
    }

  # kustomization_resource.example["apps_v1_Deployment|~X|test"] will be created
  + resource "kustomization_resource" "example" {
      + id       = (known after apply)
      + manifest = jsonencode(
            {
              + apiVersion = "apps/v1"
              + kind       = "Deployment"
              + metadata   = {
                  + creationTimestamp = null
                  + labels            = {
                      + app = "test"
                    }
                  + name              = "test"
                }
              + spec       = {
                  + replicas = 1
                  + selector = {
                      + matchLabels = {
                          + app = "test"
                        }
                    }
                  + strategy = {}
                  + template = {
                      + metadata = {
                          + creationTimestamp = null
                          + labels            = {
                              + app = "test"
                            }
                        }
                      + spec     = {
                          + containers = [
                              + {
                                  + image     = "nginx"
                                  + name      = "nginx"
                                  + resources = {}
                                },
                            ]
                        }
                    }
                }
              + status     = {}
            }
        )
    }

  # kustomization_resource.example["networking.k8s.io_v1beta1_Ingress|~X|test"] will be created
  + resource "kustomization_resource" "example" {
      + id       = (known after apply)
      + manifest = jsonencode(
            {
              + apiVersion = "networking.k8s.io/v1beta1"
              + kind       = "Ingress"
              + metadata   = {
                  + annotations = {
                      + nginx.ingress.kubernetes.io/rewrite-target = "/"
                    }
                  + name        = "test"
                }
              + spec       = {
                  + rules = [
                      + {
                          + http = {
                              + paths = [
                                  + {
                                      + backend = {
                                          + serviceName = "test"
                                          + servicePort = 80
                                        }
                                      + path    = "/testpath"
                                    },
                                ]
                            }
                        },
                    ]
                }
            }
        )
    }

  # kustomization_resource.example["~G_v1_Service|~X|test"] will be created
  + resource "kustomization_resource" "example" {
      + id       = (known after apply)
      + manifest = jsonencode(
            {
              + apiVersion = "v1"
              + kind       = "Service"
              + metadata   = {
                  + creationTimestamp = null
                  + labels            = {
                      + app = "test"
                    }
                  + name              = "test"
                }
              + spec       = {
                  + ports    = [
                      + {
                          + name       = "http"
                          + port       = 80
                          + protocol   = "TCP"
                          + targetPort = 80
                        },
                    ]
                  + selector = {
                      + app = "test"
                    }
                  + type     = "ClusterIP"
                }
              + status     = {
                  + loadBalancer = {}
                }
            }
        )
    }

Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

Your proposed implementation will error out on `terraform plan`:

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

  on main.tf line 7, in provider "kustomization":
   7: provider "kustomization" {
```

I don't know if the fallback to this default config is the best option. But it is what the `kubectl` source code does and it provides the desired result. I'm open for a different implementation if it does not change this behavior.

**Comment by maxiaohao** [comment]
Couple of feedback items here:

(1)
I've installed `terraform-provider-kind` and played with your `kind` example code (with some legit kustomization stuff under `base`). The `terraform plan` turned out to be working with both master branch build and this PR's build. 

I noted once the local cluster is provisioned by `kind`, I did have a local cluster entry named `kind-test` added to my existing `~/.kube/config` file.

Then I tried to reproduce the error you got, I deleted the file `~/.kube/config` then I got a similar one using build from my PR:
```
Error: open /home/xma11/.kube/config: no such file or directory

  on main.tf line 7, in provider "kustomization":
   7: provider "kustomization" {
```
while master branch's build still works (same as your test result). 

Keep in mind that in my PR we don't construct default client at all. 

Further, I note in the example code you have:
```
provider "kustomization" {
  kubeconfig_raw = kind.example.kubeconfig
}
```
which indicates the `kubeconfig_raw` is used and that means there is no chance for the default k8s client to be used (in either impl), right?
Here I got confused: Did the master branch code (having fallback to default client) really use `kind.example.kubeconfig` as `kubeconfig_raw` successfully? The answer seemed no, because in that way my PR build should work with it in the first place too even without a need to resort to `~/.kube/config`. So I just roughly assert `kind.example.kubeconfig` is valued empty, though I didn't look into that deeper by debugging etc. 

To be short, this doesn't sound a very good example as it doesn't seem to be different from having:
```
provider "kustomization" {
  kubeconfig_raw = "a bad value"
  kubeconfig_path = "a path doesn't exist"
}
``` 
when using master branch build it identically falls back to the default client and can still get the terraform plan through successfully. 


(2)
> But it is what the kubectl source code does and it provides the desired result.

I think kubectl falls back to `localhost:8080` only if it can't find any file under `$KUBECONFIG` or `~/.kube/config` etc. If it finds something in the criteria, it still targets to it and stick to it, despite a success or failure as the final result of an api call. But when things come to this terraform provider, the problematic scenario I see is like `try one target -> failure -> try another -> failure -> try defalut client -> success`.

To be honest I am still not convinced to keep a silent fallback to point to a local cluster. If having some mis-configured `kubeconfig_raw` and `kubeconfig_path`, I'd rather only see an error that can lead me to investigate my `kubeconfig_raw`/`kubeconfig_path` why the provider has failed to connect to the targeted cluster, even if I have a local cluster running. In other words, the local cluster shouldn't be touched unless we explicitly ask the provider to point to it.

However, I do see the value of constructing a default client to the local cluster per your example: it is super convenient and no need of an existing `~/.kube/config` for applying stuff to a ready-to-play local environment in one terraform apply. I'd then propose adding another flag for people who want to always only safely scope all operations within the cluster they expect, like this:
```
provider "kustomization" {

  kubeconfig_raw = ...
  kubeconfig_path = ...
  context = ...

  // Optional flag (false by default) to disable fallback to default kubernetes client that points to
  // the cluster running on localhost when kubeconfig_raw or kubeconfig_path fails to work
  disable_local_cluster_fallback = true
}
```
That way your `kind` example would still work with a zero configuration:
```
provider "kustomization" {}
```
Note that doesn't mean allowing the old try-and-fallback route of `kubeconfig_raw -> kubeconfig_path -> default client`,
but the new logic is supposed to be like (when local cluster fallback enabled):
- `kubeconfig_raw` is set and fails -> use default client
- `kubeconfig_raw` is unset and `kubeconfig_path` fails -> use default client

**Comment by maxiaohao** [comment]
I've pushed the implementation of the new flag `disable_local_cluster_fallback` per the idea I raised in (2) above. 
Tested it a bit locally with the `kind` example and a few scenario, looks to be working as expected. Please review again @pst and see if it is acceptable. Thank you!

**Comment by pst** [comment]
I think this PR is getting out of hand. Let's focus this PR exclusively on adding the context feature. Ability to choose a context and default fallback yes or no have nothing to do with each other.

I still feel you misunderstand the use case for the fallback. The provider has to work during plan, even if given NO valid auth information in any way. Because there are cases, where that info will only exist after the `apply` has run.

I use this in all the provider implementations for the Kubestack framework so that clusters and cluster services can be provisioned from scratch in one run. https://github.com/kbst/terraform-kubestack

**Comment by maxiaohao** [comment]
Closing this in favour of #28.

**Pull request closed without merging**
